export const csvHeaders = [
    { label: 'reportId', key: 'report.reportId' },
    { label: 'installStatus', key: 'report.installStatus' },
    { label: 'jobId', key: 'report.job.jobId' },
    { label: 'type', key: 'report.job.type' },
    { label: 'installationLocale', key: 'report.job.installationLocale' },
    { label: 'dependency', key: 'report.job.dependency' },
    { label: 'org', key: 'report.job.org' },
    { label: 'installerId', key: 'report.job.installer.installerId' },
    { label: 'productName', key: 'report.job.installer.productName' },
    { label: 'sapCode', key: 'report.job.installer.sapCode' },
    { label: 'version', key: 'report.job.installer.version' },
    { label: 'platform', key: 'report.job.installer.platform' },
    { label: 'subProduct', key: 'report.job.installer.subProduct' },
    { label: 'type', key: 'report.job.installer.type' },
    { label: 'locales', key: 'report.job.installer.locales' },
    { label: 'buildServer', key: 'report.job.installer.buildServer' },
    { label: 'rootPath', key: 'report.job.installer.rootPath' },
    { label: 'buildNo', key: 'report.job.installer.buildNo' },
    { label: 'lastModified', key: 'report.job.installer.lastModified' },
    { label: 'installerFormat', key: 'report.job.installer.installerFormat' },
    { label: 'buildPath', key: 'report.job.installer.buildPath' },
    { label: 'installation_locale', key: 'report.job.installer.installation_locale' },
    { label: 'serverBuildPath', key: 'report.job.installer.serverBuildPath' },
    { label: 'installerState', key: 'report.job.installer.installerState' },
    { label: 'dependencies', key: 'report.job.installer.dependencies' },
    { label: 'id', key: 'report.job.host.id' },
    { label: 'domain', key: 'report.job.host.domain' },
    { label: 'machineName', key: 'report.job.host.machineName' },
    { label: 'osLanguage', key: 'report.job.host.osLanguage' },
    { label: 'osArchitecture', key: 'report.job.host.osArchitecture' },
    { label: 'osVersion', key: 'report.job.host.osVersion' },
    { label: 'ipaddress', key: 'report.job.host.ipaddress' },
    { label: 'user', key: 'report.job.host.user' },
    { label: 'details exit_code', key: 'details[0].exit_code' },
    { label: 'details detail', key: 'details[0].detail' },
    { label: 'details output', key: 'details[0].output' },
    { label: 'details exit_code', key: 'details[1].detail' },
    { label: 'details detail', key: 'details[1].exit_code' },
    { label: 'details output', key: 'details[1].output' },
    { label: 'details exit_code', key: 'details[2].exit_code' },
    { label: 'details detail', key: 'details[2].detail' },
    { label: 'details output', key: 'details[2].output' },
    { label: 'details exit_code', key: 'details[3].exit_code' },
    { label: 'details detail', key: 'details[3].detail' },
    { label: 'details output', key: 'details[3].output' },
    { label: 'details exit_code', key: 'details[4].exit_code' },
    { label: 'details detail', key: 'details[4].detail' },
    { label: 'details output', key: 'details[4].output' },
    { label: 'details exit_code', key: 'details[5].exit_code' },
    { label: 'details detail', key: 'details[5].detail' },
    { label: 'details output', key: 'details[5].output' },
    { label: 'details exit_code', key: 'details[6].exit_code' },
    { label: 'details detail', key: 'details[6].detail' },
    { label: 'details output', key: 'details[6].output' },
    { label: 'details exit_code', key: 'details[7].exit_code' },
    { label: 'details detail', key: 'details[7].detail' },
    { label: 'details output', key: 'details[7].output' },
    { label: 'details exit_code', key: 'details[8].exit_code' },
    { label: 'details detail', key: 'details[8].detail' },
    { label: 'details output', key: 'details[8].output' },
    { label: 'details exit_code', key: 'details[9].exit_code' },
    { label: 'details detail', key: 'details[9].detail' },
    { label: 'details output', key: 'details[9].output' }

  ];